### ISSUE TITLE
LTS will download 18.04.2 instead of the latest .3

### ISSUE THREAD

**Issue by nobuto-m** [powersj/ubuntu-iso-download#4]
The expected result is to download 18.04.3.

```
$ snap list ubuntu-iso-download
Name                 Version  Rev  Tracking  Publisher  Notes
ubuntu-iso-download  125e8ee  101  stable    powersj    -
```

```
$ ubuntu-iso-download --dry-run server 
Ubuntu Server ISO on bionic
http://releases.ubuntu.com/18.04.2/ubuntu-18.04.2-live-server-amd64.iso
```

**Comment by powersj** [comment]
It appears that the root cause is https://changelogs.ubuntu.com/meta-release is missing 18.04.3. 

I have asked for an update to be made to that. I have another python project, ubuntu-release-info, that parses that URL for what the latest releases are. That is what ubuntu-iso-download then reads to determine the latest URL.

**Comment by nobuto-m** [comment]
Thanks for the clarification. Now the metadata has been updated and --dry-run give me an expected one :+1: 

```
$ ubuntu-iso-download --dry-run server
Ubuntu Server ISO on bionic
http://releases.ubuntu.com/18.04.3/ubuntu-18.04.3-live-server-amd64.iso
```
