### ISSUE TITLE
SHA-256 hash mismatch when downloading 20.04.02

### ISSUE THREAD

**Issue by 0Llve** [powersj/ubuntu-iso-download#6]
I've just tried this : `for flavor in {budgie,desktop,kubuntu,lubuntu,mate,server,studio,xubuntu}; do ubuntu-iso-download $flavor;done`
with the last snap version (2020.06.21+git5f3db12).
This is the result :

```
Ubuntu Budgie ISO on focal
Downloading ubuntu-budgie-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/ubuntu-budgie/releases/focal/release
100%|████| 2.49G/2.49G [02:15<00:00, 18.4MB/s]
Oops: SHA-256 hash mismatch!
Ubuntu Desktop ISO on focal
Downloading ubuntu-20.04.2-desktop-amd64.iso from http://releases.ubuntu.com/20.04.2
100%|████| 281/281 [00:00<00:00, 165kB/s]
Oops: SHA-256 hash mismatch!
Kubuntu ISO on focal
Downloading kubuntu-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/kubuntu/releases/focal/release
100%|████| 2.64G/2.64G [03:19<00:00, 7.81MB/s]
Oops: SHA-256 hash mismatch!
Lubuntu ISO on focal
Downloading lubuntu-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/lubuntu/releases/focal/release
100%|████| 1.82G/1.82G [02:00<00:00, 15.0MB/s]
Ubuntu MATE ISO on focal
Downloading ubuntu-mate-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/ubuntu-mate/releases/focal/release
100%|████| 2.62G/2.62G [02:20<00:00, 18.7MB/s]
Oops: SHA-256 hash mismatch!
Ubuntu Server ISO on focal
Downloading ubuntu-20.04.2-live-server-amd64.iso from http://releases.ubuntu.com/20.04.2
100%|████| 1.22G/1.22G [00:59<00:00, 23.7MB/s]
Ubuntu Studio ISO on focal
Downloading ubuntustudio-20.04.2-dvd-amd64.iso from http://cdimage.ubuntu.com/ubuntustudio/releases/focal/release
100%|████| 3.75G/3.75G [03:13<00:00, 19.4MB/s]
Oops: SHA-256 hash mismatch!
Xubuntu ISO on focal
Downloading xubuntu-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/xubuntu/releases/focal/release
100%|████| 1.74G/1.74G [01:30<00:00, 22.1MB/s]
Oops: SHA-256 hash mismatch!
```
`
As you can see only server and lubuntu are OK with hash check for the last LTS (20.04.2).

thanks

**Comment by powersj** [comment]
Hi! Thanks for taking the time to file a bug to let me know about this I really appreciate it!

I confirmed the issue when downloading the budgie ISO. Running with `--debug` will show the SHAs used to compare. The first is the value from the SHA256SUM file and the second is what was downloaded:

```shell
ubuntu-iso-download --debug budgie focal
Ubuntu Budgie ISO on focal
Downloading ubuntu-budgie-20.04.2-desktop-amd64.iso from http://cdimage.ubuntu.com/ubuntu-budgie/releases/focal/release
100%|████████████████████████████████████████| 2.49G/2.49G [04:30<00:00, 9.19MB/s]
Verifying SHA-256
c7f2a83fea81bfcb381b5d66799f9540a7bbd347591c3a40ee6fc9cffada159b
42c1d0f53dbc0bbdac0058fd1cdd5f75f234f432cf8b87103ce114804baa38f7
Oops: SHA-256 hash mismatch!
```

I went and looked at the [SHA256SUMs](https://cdimage.ubuntu.com/ubuntu-budgie/releases/focal/release/SHA256SUMS) and it shows:

```text
839f84520bc6edfebd35231486a30035ac74aae64c17bf4d4eb24a437a3ede93 *ubuntu-budgie-20.04.1-desktop-amd64.iso
42c1d0f53dbc0bbdac0058fd1cdd5f75f234f432cf8b87103ce114804baa38f7 *ubuntu-budgie-20.04.2-desktop-amd64.iso
c7f2a83fea81bfcb381b5d66799f9540a7bbd347591c3a40ee6fc9cffada159b *ubuntu-budgie-20.04.2.0-desktop-amd64.iso
```

The logic to figure out what SHA to use was wrong and matching on the last entry with a matching flavor and arch. When it should have been matching on the filename itself. I was already using this logic with the mini ISO, but I cannot recall why I was doing it differently with the other ISOs.

This reveals a second issue. The recent re-spin of the 20.04 ISOs produced a new version: `20.04.2.0`, which is not getting downloaded. I determine the version to download based on my library [ubuntu_release_info](https://github.com/powersj/ubuntu-release-info), which determines versions from [https://changelogs.ubuntu.com/meta-release](https://changelogs.ubuntu.com/meta-release). This does not work for an extra point release like `20.04.2.0`.

Which of course then when I dig in, this reminds me why I was using the above logic to get the latest ISO. In order to find the latest point release, I was looking at the SHA256SUM file for the last file. I have removed the filename logic and use the latest filename for the SHA256SUM file to determine what the latest file actually is.

I have pushed all my changes, released a new version to PyPI and the new snap is building now. It will be version 21.1.

**Comment by powersj** [comment]
snap version `2021.02.13+git3d93a1a` released! Please let me know if you run into any further issues and thanks again for reporting this!

**Comment by 0Llve** [comment]
It is me who thank YOU :)
